year_messages = 'додайте рік фотографії:-'
month_messages = 'додайте місяць фотографії:-'
day_messages = 'додайте день фотографії:-'
validator_data = 'Введіть дату фотографії у такому форматі YYYY-MM-DD.\nСпробуйте знову'
user_input_except = 'Використовейте лише цифри для заповнення полів'
connection_error_messages = 'Помилка з\'єднання'
